### ISSUE TITLE
401: Unauthorized

### ISSUE THREAD

**Issue by HelSanYUL** [EnArvy/Discord-Gemini-Chatbot#5]
When running python3 bot.py

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/http.py", line 803, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/usr/local/lib/python3.10/dist-packages/discord/http.py", line 745, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

I'm I missing something. 
I created the .env with both tokens and I'm getting this

Thanks

**Comment by HelSanYUL** [comment]
Found the issue. Typo in the Bot Token.
Sorry for the trouble

**Comment by HelSanYUL** [comment]
Closing issue
